import type { ProspectConfig, Service, DesignDirection } from "./types";

const baseDesign: DesignDirection = {
  theme: "light-technical",
  navbar: "NavbarTransparent",
  hero: "HeroEngineered",
  serviceLayout: "ServiceEditorial",
  trustLayout: "TrustRating",
  processLayout: "ProcessManufacture",
  ctaLayout: "CtaEngineered",
  imageTreatment: "PhotoCover",
  animationLevel: "high",
  useSvgScenes: false,
};

const standardOrder: Service["sectionOrder"] = ["hero", "overview", "specifications", "applications", "process", "trust", "cta"];
const compactOrder: Service["sectionOrder"] = ["hero", "overview", "specifications", "applications", "trust", "cta"];

/* Stock hero/banner photos (Unsplash, 1920×1080 landscape) — replace low-res live-site banners */
const S = "https://images.unsplash.com/photo";
const stock = {
  factory: `${S}-1504307651254-35680f356dfd?w=1920&h=1080&fit=crop&q=80`,
  workshop: `${S}-1519389950473-47ba0277781c?w=1920&h=1080&fit=crop&q=80`,
  plant: `${S}-1581094794329-c8112a89af12?w=1920&h=1080&fit=crop&q=80`,
  building: `${S}-1441974231531-c6227db76b6e?w=1920&h=1080&fit=crop&q=80`,
  restaurant: `${S}-1556909114-f6e7ad7d3136?w=1920&h=1080&fit=crop&q=80`,
  food: `${S}-1504674900247-0877df9cc836?w=1920&h=1080&fit=crop&q=80`,
  catering: `${S}-1482049016688-2d3e1b311543?w=1920&h=1080&fit=crop&q=80`,
  cityscape: `${S}-1473448912268-2022ce9509d8?w=1920&h=1080&fit=crop&q=80`,
  urban: `${S}-1497366216548-37526070297c?w=1920&h=1080&fit=crop&q=80`,
  office: `${S}-1481627834876-b7833e8f5570?w=1920&h=1080&fit=crop&q=80`,
  city: `${S}-1560448204-e02f11c3d0e2?w=1920&h=1080&fit=crop&q=80`,
  home: `${S}-1513475382585-d06e58bcb0e0?w=1920&h=1080&fit=crop&q=80`,
};

/* ------------------------------------------------------------------ */
/* GEO GROUP GLOBAL — geogroupglobal.com                                */
/* ------------------------------------------------------------------ */

const geoAssets = "https://geogroupglobal.com/assets";

const geo: ProspectConfig = {
  slug: "geo-group-global",
  companyName: "Geo Group Global LLC",
  displayName: "Geo Group",
  industry: "hvac",
  established: 1977,
  location: "Sharjah, United Arab Emirates",
  slogan: "Quality, that is Guaranteed.",
  metaRole: "heating, cooling, chiller & generator engineers",
  hero: {
    kicker: "Est. 1977 · Sharjah, UAE · Heating, cooling & power engineering",
    headlineTop: "Cooling, power and",
    headlineAccent: "guaranteed quality",
    headlineBottom: "since 1977.",
    subline:
      "Geo Group engineers, rents and maintains chillers, generators, air handling units and ducting for the Gulf's toughest sites — through Geo Rental, Geonair and Geo Electrical, backed by 45+ years of trading.",
  },
  branding: {
    primaryColor: "#0B4DA0",
    secondaryColor: "#073E85",
    accentColor: "#0EA5E9",
    tintColor: "#E8F1FB",
  },
  contact: {
    email: "info@geogroupglobal.com",
    address: "Sharjah, United Arab Emirates",
    phone: "+971 6 542 0603",
  },
  socialProof: {
    googleRating: 4.2,
    reviewCount: 109,
    keywords: ["Heating & Cooling", "Chillers", "Generators", "HVAC Rental", "AHU & Ducting"],
  },
  certifications: [],
  markets: ["Sharjah", "Dubai", "Abu Dhabi", "Northern Emirates", "GCC"],
  facilities: [
    "Geo Rental — chillers, generators, fuel tanks & district cooling",
    "Geonair — packaged air conditioning & heating equipment",
    "Geo Electrical — HVAC electrical, pump & control works",
    "Geo Global FZE — international division",
  ],
  images: {
    officeBanner: stock.plant,
    aerial: stock.cityscape,
    factorySharjah: stock.factory,
    heroPoster: stock.workshop,
    showreelPoster: stock.city,
  },
  projects: [
    {
      name: "Chiller, Generator & Fuel Tank — Rental Site",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Geonair Water Chiller Supply",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Rooftop AHU Installation",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Rental Generator & Fuel Site",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Ducting & Mechanical Works",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Package Unit Installation",
      location: "Sharjah, UAE",
      img: stock.building,
    },
  ],
  featuredServiceSlug: "geonair-water-chillers",
  designDirection: baseDesign,
  automation: [
    "Enquiry received",
    "AI qualification",
    "Service identified",
    "Lead created",
    "Team notified",
    "Follow-up scheduled",
  ],
  cta: {
    heading: "Let's cool and power your next site.",
    body: "Tell Geo Group what you need to heat, cool or keep running — a chiller, a generator, a full Geonair system or a rental — and the engineering team will come back with the right gear and a guaranteed-quality plan.",
  },
  voice: {
    brand: { initial: "GG", line1: "GEO GROUP", line2: "Est. 1977 · Sharjah" },
    nav: { homeBack: "Back to Geo", quoteLabel: "Request a quote" },
    hero: {
      primaryCta: "Talk to the Geo team",
      secondaryCta: "Explore Geonair products",
      heroImageAlt: "Geo Group — heating, cooling and power engineering since 1977",
      ghostText: "QUALITY · GUARANTEED · 1977",
      stats: [
        { value: "47", label: "Years of heating, cooling & power — since 1977" },
        { value: "6", label: "Divisions — Rental · Geonair · Electrical · Global FZE" },
        { value: "4.2", label: "Google rating · 109 reviews" },
        { value: "7", label: "Product families in the Geonair range" },
      ],
      contactCardLabel: "Call Geo Group — toll line",
      chipsHeading: "Multi-disciplinary engineering",
      scrollCue: "Inside Geo Group",
    },
    trustLines: [
      "Quality, that is Guaranteed — since 1977",
      "Rental to permanent installations",
    ],
    servicesKicker: "Divisions & products",
    servicesHomeHeading: "Cool the building AND keep the power on",
    servicesHomeBlurb:
      "From Geonair chiller range through Geo Rental's generators to Geo Electrical installs — one group engineered for the whole site.",
    servicesIndexHeading: "The complete {displayName} capability",
    servicesIndexBlurb:
      "{count} product and service lines across the Geo Group — designed for rental or permanent installation, every one with guaranteed quality.",
    serviceDetail: {
      overviewHeadingPrefix: "Geo Group",
      figureCaptionSuffix: "engineered and supplied by",
      badge: "Guaranteed quality",
      footnote:
        "Every Geonair system is engineered and tested by Geo Group and backed by the group's warranty — installed, commissioned and, where needed, continued on rental or AMC.",
      },
    assistant: { fallbackEmail: "info@geogroupglobal.com" },
    },
  services: [
    {
      slug: "geonair-water-chillers",
      sectionOrder: standardOrder,
      name: "Geonair Water Chillers",
      shortName: "Chillers",
      tagline: "Air-cooled and water-cooled chillers from 1 to 60 TR — built for process and comfort.",
      summary:
        "The Geonair water chiller range covers 1 TR to 60 TR cooling across air-conditioning and process applications — packaged, factory tested and ready to pair with Geo's chillers-on-crane installation and rental services.",
      capacity: "1 – 60 TR",
      series: [
        "1 · 2 · 3 · 5 · 7.5 TR — small packaged chillers",
        "10 · 15 · 20 · 25 · 30 TR — commercial and light process",
        "60 TR — heavy industrial cooling",
      ],
      standards: [],
      applications: ["Commercial buildings", "Industrial process cooling", "Food & beverage", "Equipment rooms", "District cooling"],
      features: [
        "Packaged, factory-tested construction",
        "Matched to Geo Rental for temporary or permanent duty",
        "Commissioned and supported by the Geo engineering team",
      ],
      image: stock.building,
    },
    {
      slug: "geonair-package-units",
      name: "Geonair Package Units",
      sectionOrder: compactOrder,
      shortName: "Package",
      tagline: "Self-contained package units for rooftop and ground installation.",
      summary:
        "Geonair package units arrive self-contained — compressor, coils and controls in one cabinet — so site work is limited to ducting and power. Ideal for the Gulf's rooftop installs.",
      capacity: "Compact → industrial",
      series: ["Rooftop package units", "Ground package units", "Custom industrial build"],
      standards: [],
      applications: ["Warehouses", "Mosques", "Retail", "Labour camps", "Industrial halls"],
      features: [
        "Factory assembled and charged",
        "Custom industrial fabrication available",
        "Rental-ready configuration on request",
      ],
      image: stock.building,
    },
    {
      slug: "geonair-air-handling-units",
      name: "Geonair Air Handling Units",
      sectionOrder: compactOrder,
      shortName: "AHU",
      tagline: "Modular air handling units engineered for Gulf ambient conditions.",
      summary:
        "Geonair air handling units are fabricated in modular sections for indoor and outdoor installation — built to match the cooling load of commercial and industrial spaces across the Emirates.",
      capacity: "Modular · custom sizes",
      series: ["Indoor modular AHUs", "Outdoor weather-proofed AHUs"],
      standards: [],
      applications: ["Commercial buildings", "Industrial plants", "Hospitals", "Hotels", "Factories"],
      features: [
        "Modular sectional construction",
        "Gulf-climate weatherproofing on outdoor units",
        "Commissioned to the design cooling load",
      ],
      image: stock.building,
    },
    {
      slug: "geonair-ducted-split-units",
      name: "Geonair Ducted Split Units",
      sectionOrder: compactOrder,
      shortName: "Ducted Split",
      tagline: "Concealed ducted split systems with a clean, quiet finish.",
      summary:
        "Geonair ducted split units hide above the ceiling and push conditioned air through discreet grilles — a neat answer for offices, villas and retail where visible units won't do.",
      capacity: "Split range",
      series: ["Concealed ducted split units"],
      standards: [],
      applications: ["Villas", "Offices", "Retail", "Apartments"],
      features: [
        "Concealed installation above false ceilings",
        "Quiet operation",
        "Clean grille finishes",
      ],
      image: stock.building,
    },
    {
      slug: "geonair-wall-mounted-units",
      name: "Geonair Wall-Mounted Units",
      sectionOrder: compactOrder,
      shortName: "Wall Mount",
      tagline: "Wall-mounted splits engineered for reliability in harsh climates.",
      summary:
        "Geonair wall-mounted split units bring dependable, serviceable cooling to rooms, offices and staff areas — with compressors and coils selected for the Gulf's heat.",
      capacity: "Split range",
      series: ["Wall-mounted split systems"],
      standards: [],
      applications: ["Offices", "Staff rooms", "Retail", "Residential"],
      features: [
        "Reliable Gulf-climate engineering",
        "Quick installation and easy maintenance",
      ],
      image: stock.building,
    },
    {
      slug: "geonair-air-curtains",
      name: "Geonair Air Curtains",
      sectionOrder: compactOrder,
      shortName: "Air Curtain",
      tagline: "Cross-flow air curtains that hold your cool — at the door.",
      summary:
        "Geonair air curtains create an invisible barrier at entrances and loading bays, holding conditioned air inside while the doors stay open for business.",
      capacity: "Door widths",
      series: ["Cross-flow air curtain range"],
      standards: [],
      applications: ["Shop entrances", "Restaurants", "Warehouses", "Cold rooms"],
      features: [
        "Holds conditioned air at open doors",
        "Reduces load on the HVAC system",
      ],
      image: stock.building,
    },
    {
      slug: "geonair-floor-standing-units",
      name: "Geonair Floor-Standing Units",
      sectionOrder: compactOrder,
      shortName: "Floor Standing",
      tagline: "Floor-standing packaged units for spaces where wall units won't fit.",
      summary:
        "Geonair floor-standing units sit directly on the floor and push air at low level — ideal for halls, workshops and rooms with heavy internal loads or awkward walls.",
      capacity: "Freestanding range",
      series: ["Freestanding floor units", "Custom industrial freestanding units"],
      standards: [],
      applications: ["Workshops", "Event halls", "Factories", "Retail floors"],
      features: [
        "No wall mounting required",
        "Custom industrial sizes available",
      ],
      image: stock.building,
    },
    {
      slug: "domestic-water-chillers",
      name: "Domestic Water Chillers",
      shortName: "Water Chiller",
      sectionOrder: compactOrder,
      tagline: "Quiet, compact chillers for domestic and small-commercial cooling.",
      summary:
        "The Geonair domestic water chiller line pairs chilled water with fan coil units for villas, apartments and small commercial spaces — sized quietly and engineered for efficiency.",
      capacity: "Fan coil matched",
      series: ["Domestic water chillers", "Matched fan coil units"],
      standards: [],
      applications: ["Villas", "Apartments", "Small offices", "Retail"],
      features: [
        "Compact, low-noise design",
        "Matched fan coil units",
        "Simple installation",
      ],
      image: stock.building,
    },
  ],
};

const aljunaid: ProspectConfig = {
  slug: "aljunaid",
  companyName: "Al Junaid Air Conditioning LLC",
  displayName: "Aljunaid",
  industry: "hvac",
  established: 2008,
  location: "Sajja Industrial Area, Sharjah, United Arab Emirates",
  slogan: "Cooling equipment, engineered and delivered.",
  metaRole: "packaged air conditioning & refrigeration manufacturer",
  hero: {
    kicker: "Est. 2008 · Sajja Industrial Area, Sharjah · Packaged AC manufacturer",
    headlineTop: "Manufacturing the Gulf's",
    headlineAccent: "air conditioning",
    headlineBottom: "from Sharjah's Sajja district.",
    subline:
      "Aljunaid designs and builds packaged air conditioning, chiller and refrigeration equipment at its Sajja factory — serving brand partners and industrial clients across the UAE since 2008.",
  },
  branding: {
    primaryColor: "#E85D26",
    secondaryColor: "#C2471C",
    accentColor: "#F5A623",
    tintColor: "#FDF0E7",
  },
  contact: {
    email: "",
    address: "P.O. Box 61401, Sajja Industrial Area, Sharjah, United Arab Emirates",
    phone: "+971 50 484 9694",
  },
  socialProof: {
    googleRating: 4.8,
    reviewCount: 239,
    keywords: ["Packaged AC", "Refrigeration", "Industrial Cooling", "Equipment Manufacturing"],
  },
  certifications: [],
  markets: ["Sharjah", "Dubai", "Northern Emirates", "UAE-wide delivery"],
  facilities: [
    "Sajja Industrial Area — manufacturing base",
    "Packaged unit & chiller fabrication in-house",
    "Panel shop for cold rooms & walk-in freezers",
  ],
  images: {
    officeBanner: stock.factory,
    aerial: stock.cityscape,
    factorySharjah: stock.workshop,
    heroPoster: stock.plant,
    showreelPoster: stock.city,
  },
  projects: [
    {
      name: "Industrial Chiller Systems",
      location: "Sharjah, UAE",
      img: stock.workshop,
    },
    {
      name: "Packaged Unit Fabrication",
      location: "Sharjah, UAE",
      img: stock.workshop,
    },
    {
      name: "Cold Room Panel Installation",
      location: "Sajja Industrial Area, Sharjah",
      img: stock.workshop,
    },
    {
      name: "Refrigeration System Delivery",
      location: "UAE",
      img: stock.workshop,
    },
  ],
  featuredServiceSlug: "packaged-air-conditioning",
  designDirection: baseDesign,
  automation: [
    "Enquiry received",
    "AI qualification",
    "Product matched",
    "Lead created",
    "Factory team notified",
    "Follow-up scheduled",
  ],
  cta: {
    heading: "Let's manufacture for your next project.",
    body: "Send Aljunaid your cooling requirements — packaged units, chillers, cold rooms or refrigeration — and the Sajja factory team will respond with pricing, lead times and technical support.",
  },
  voice: {
    brand: { initial: "AJ", line1: "ALJUNAID", line2: "Est. 2008 · Sharjah" },
    nav: { homeBack: "Back to Aljunaid", quoteLabel: "Request a quote" },
    hero: {
      primaryCta: "Talk to the factory team",
      secondaryCta: "Explore the product range",
      heroImageAlt: "Aljunaid — packaged air conditioning engineered in Sharjah",
      ghostText: "MADE IN SHARJAH · EST 2008",
      stats: [
        { value: "2008", label: "Manufacturing since — Sajja Industrial Area, Sharjah" },
        { value: "4.8", label: "Google rating · 239 reviews" },
        { value: "100%", label: "In-house fabrication" },
        { value: "24/7", label: "Delivery & commissioning support" },
      ],
      contactCardLabel: "WhatsApp the team — fastest route",
      chipsHeading: "Engineering-driven manufacturer",
      scrollCue: "Inside the Sajja factory",
    },
    trustLines: [
      "Manufactured in Sharjah — not imported",
      "In-house fabrication across the range",
    ],
    servicesKicker: "Product lines",
    servicesHomeHeading: "Built in Sharjah, delivered across the UAE",
    servicesHomeBlurb:
      "Every product line is fabricated at the Aljunaid factory in Sajja — packaged units, chillers, refrigeration and cold rooms, engineered for Gulf duty cycle.",
    servicesIndexHeading: "The complete {displayName} range",
    servicesIndexBlurb:
      "{count} product lines, all fabricated in-house at Sajja Industrial Area — engineered for the Gulf's climate and working conditions.",
    serviceDetail: {
      overviewHeadingPrefix: "Aljunaid",
      figureCaptionSuffix: "manufactured by",
      badge: "Factory engineered",
      footnote:
        "Every Aljunaid system is fabricated and tested in-house before delivery — engineered for Gulf ambient conditions and backed by the factory team.",
      },
    assistant: { fallbackEmail: "+971 50 484 9694" },
    },
  services: [
    {
      slug: "packaged-air-conditioning",
      sectionOrder: standardOrder,
      name: "Packaged Air Conditioning",
      shortName: "Packaged",
      tagline: "Self-contained packaged units manufactured for outdoor Gulf duty.",
      summary:
        "Aljunaid manufactures packaged air conditioning units for rooftop and ground installation — self-contained, outdoor-ready and fabricated in the Sajja factory for the Gulf's severe climate.",
      capacity: "Packaged range",
      series: ["Rooftop packaged units", "Ground packaged units"],
      standards: [],
      applications: ["Warehouses", "Industrial halls", "Labour camps", "Retail", "Event spaces"],
      features: [
        "In-house fabrication and assembly",
        "Weather-proofed for outdoor installation",
        "Factory support through commissioning",
      ],
      image: stock.workshop,
    },
    {
      slug: "chiller-units",
      name: "Chiller Units",
      sectionOrder: compactOrder,
      shortName: "Chillers",
      tagline: "Packaged chillers engineered for process and building cooling.",
      summary:
        "Aljunaid's chiller line covers the cooling loads of commercial and industrial buildings — engineered, assembled and tested at the Sharjah factory before delivery.",
      capacity: "Chiller range",
      series: ["Air-cooled packaged chillers"],
      standards: [],
      applications: ["Commercial buildings", "Industrial process", "Hotels", "Stores"],
      features: ["Factory tested", "Rental and permanent configurations"],
      image: stock.workshop,
    },
    {
      slug: "cold-room-freezer-panels",
      name: "Cold Room & Freezer Panels",
      sectionOrder: compactOrder,
      shortName: "Cold Rooms",
      tagline: "Insulated panels fabricated in-house for cold rooms and freezers.",
      summary:
        "Aljunaid's panel shop fabricates insulated cold room and walk-in freezer panels — produced in Sajja and installed to hold food-safe temperatures year-round.",
      capacity: "Walk-ins · freezers",
      series: ["Cold room panels", "Walk-in freezer panels"],
      standards: [],
      applications: ["Restaurants", "Supermarkets", "Food storage", "Catering"],
      features: [
        "In-house panel fabrication",
        "Fast, modular assembly",
        "Matched refrigeration packages",
      ],
      image: stock.workshop,
    },
    {
      slug: "refrigeration-units",
      name: "Refrigeration Units",
      sectionOrder: compactOrder,
      shortName: "Refrigeration",
      tagline: "Display and storage refrigeration engineered for food businesses.",
      summary:
        "The refrigeration line covers cold rooms, chillers and display refrigeration for shops and food service — built for continuous duty and easy maintenance.",
      capacity: "Storage · display",
      series: ["Storage refrigeration", "Display refrigeration"],
      standards: [],
      applications: ["Grocery & supermarkets", "Food service", "Hypermarkets", "Cold storage"],
      features: ["Energy-conscious design", "Serviceable compressors"],
      image: stock.workshop,
    },
    {
      slug: "ducted-mini-split-systems",
      name: "Ducted & Mini-Split Systems",
      sectionOrder: compactOrder,
      shortName: "Ductor",
      tagline: "Concealed ducted and mini-split cooling for smaller spaces.",
      summary:
        "For offices, villas and shops that need discreet cooling, Aljunaid supplies ducted and mini-split systems — selected, supplied and supported by the factory team.",
      capacity: "Split range",
      series: ["Ducted split units", "Mini-split units"],
      standards: [],
      applications: ["Offices", "Villas", "Retail", "Apartments"],
      features: ["Concealed installation", "Quiet operation"],
      image: stock.workshop,
    },
    {
      slug: "replacement-condensing-spare-parts",
      name: "Replacement Condensing & Spare Parts",
      shortName: "Condensers",
      sectionOrder: compactOrder,
      tagline: "Factory-direct condensing units and genuine parts support.",
      summary:
        "Aljunaid supplies replacement condensing units and genuine spare parts for its own and compatible systems — keeping existing plants running with factory-direct support.",
      capacity: "Condensing range",
      series: ["Condensing units", "Genuine spare parts"],
      standards: [],
      applications: ["System replacement", "Breakdown repair", "Plant upgrades"],
      features: ["Factory-direct supply", "Technical support"],
      image: stock.workshop,
    },
  ],
};

const atheer: ProspectConfig = {
  slug: "atheer-al-jazirah",
  companyName: "Atheer Al Jazirah General Contracting",
  displayName: "Atheer",
  industry: "contracting",
  established: 2004,
  location: "Dubai & Sharjah, United Arab Emirates",
  slogan: "Excellence with Integrity.",
  metaRole: "MEP & general contracting",
  hero: {
    kicker: "Est. 2004 · Dubai & Sharjah · MEP & general contracting",
    headlineTop: "MEP and construction,",
    headlineAccent: "delivered with integrity",
    headlineBottom: "since 2004.",
    subline:
      "Atheer Al Jazirah delivers mechanical, electrical and plumbing works plus general building — for villas, malls, mosques, schools, factories and landmarks across the UAE, from design through to handover.",
  },
  branding: {
    primaryColor: "#0E7C66",
    secondaryColor: "#0A5C4D",
    accentColor: "#14B8A6",
    tintColor: "#E6F4F1",
  },
  contact: {
    email: "",
    address: "P.O. Box 34117, Dubai, United Arab Emirates",
    phone: "+971 4 267 6022",
  },
  socialProof: {
    googleRating: 4.4,
    reviewCount: 30,
    keywords: ["MEP Contracting", "Mechanical Works", "Electrical Works", "Plumbing", "General Building"],
  },
  certifications: [],
  markets: ["Dubai", "Sharjah", "Northern Emirates", "UAE"],
  facilities: [
    "Dubai headquarters — P.O. Box 34117",
    "Sharjah branch — P.O. Box 26065",
    "In-house MEP teams — mechanical, electrical & plumbing",
  ],
  images: {
    officeBanner: stock.building,
    aerial: stock.city,
    factorySharjah: stock.cityscape,
    heroPoster: stock.office,
    showreelPoster: stock.urban,
  },
  projects: [
    {
      name: "Building Project",
      location: "UAE",
      img: stock.plant,
    },
    {
      name: "Villa MEP Works",
      location: "UAE",
      img: stock.plant,
    },
    {
      name: "Mosque Mechanical Works",
      location: "UAE",
      img: stock.plant,
    },
    {
      name: "Factory Electrical Installation",
      location: "UAE",
      img: stock.plant,
    },
    {
      name: "Mall Air Conditioning",
      location: "UAE",
      img: stock.plant,
    },
    {
      name: "School Plumbing Works",
      location: "UAE",
      img: stock.plant,
    },
  ],
  featuredServiceSlug: "mechanical-works",
  designDirection: baseDesign,
  automation: [
    "Enquiry received",
    "AI qualification",
    "Trade matched",
    "Lead created",
    "Contract team notified",
    "Follow-up scheduled",
  ],
  cta: {
    heading: "Let's build with integrity.",
    body: "Tell Atheer Al Jazirah about your project — MEP works, building construction or a full package — and the contracting team will respond with experience, references and a clear plan.",
  },
  voice: {
    brand: { initial: "AA", line1: "ATHEER", line2: "Est. 2004 · Dubai" },
    nav: { homeBack: "Back to Atheer", quoteLabel: "Discuss a project" },
    hero: {
      primaryCta: "Discuss a project",
      secondaryCta: "Explore our works",
      heroImageAlt: "Atheer Al Jazirah — MEP and general contracting since 2004",
      ghostText: "EXCELLENCE WITH INTEGRITY · 2004",
      stats: [
        { value: "2004", label: "Contracting since — Dubai & Sharjah" },
        { value: "3", label: "In-house MEP trades — mechanical · electrical · plumbing" },
        { value: "8", label: "Project categories — mosques to factories" },
        { value: "4.4", label: "Google rating · 30 reviews" },
      ],
      contactCardLabel: "Call the contracting office",
      chipsHeading: "Multi-trade contracting",
      scrollCue: "Our project portfolio",
    },
    trustLines: [
      "Excellence with Integrity — our founding principle",
      "Multi-trade MEP under one contract",
    ],
    servicesKicker: "Our trades",
    servicesHomeHeading: "Every trade your build needs — under one contract",
    servicesHomeBlurb:
      "Mechanical, electrical and plumbing works with general building behind them — one contractor, one contract, full accountability from design to handover.",
    servicesIndexHeading: "{displayName} — the complete trade package",
    servicesIndexBlurb:
      "{count} contracting trades, delivered with integrity across the UAE — from villa mechanical works to landmark building projects.",
    serviceDetail: {
      overviewHeadingPrefix: "Atheer",
      figureCaptionSuffix: "delivered by",
      badge: "Integrity guaranteed",
      footnote:
        "Every Atheer contract is delivered by in-house teams with project-level accountability — signed off at every stage from design through handover.",
      },
    assistant: { fallbackEmail: "+971 4 267 6022" },
    },
  services: [
    {
      slug: "mechanical-works",
      sectionOrder: standardOrder,
      name: "Mechanical Works",
      shortName: "Mechanical",
      tagline: "HVAC, plumbing and mechanical installation for buildings of every scale.",
      summary:
        "Atheer's mechanical division covers heating, ventilation, air conditioning and plumbing installation — from villa systems to the mechanical services of malls, mosques, schools and factories.",
      capacity: "Villa → landmark scale",
      series: ["HVAC systems", "Plumbing & drainage", "Mechanical installation"],
      standards: [],
      applications: ["Villas", "Commercial buildings", "Malls & retail", "Mosques", "Factories"],
      features: [
        "In-house mechanical teams",
        "Design-assist from tender stage",
        "Full commissioning and handover",
      ],
      image: stock.plant,
    },
    {
      slug: "electrical-works",
      name: "Electrical Works",
      sectionOrder: compactOrder,
      shortName: "Electrical",
      tagline: "Power, lighting and low-current systems installed to spec.",
      summary:
        "The electrical division delivers power distribution, lighting, earthing and low-current systems across the trades Atheer builds — coordinated with mechanical and plumbing from day one.",
      capacity: "Full electrical scope",
      series: ["Power distribution", "Lighting & controls", "Low current & security"],
      standards: [],
      applications: ["Buildings", "Malls & retail", "Industrial facilities", "Infrastructure"],
      features: ["Coordinated multi-trade delivery", "Testing & commissioning"],
      image: stock.plant,
    },
    {
      slug: "plumbing-works",
      name: "Plumbing Works",
      sectionOrder: compactOrder,
      shortName: "Plumbing",
      tagline: "Water supply, drainage and sanitary installation for every project type.",
      summary:
        "Atheer's plumbing teams install potable water, drainage and sanitary systems — sized to the building, coordinated with mechanical and electrical, and pressure tested before handover.",
      capacity: "Full plumbing scope",
      series: ["Water supply", "Drainage & sewage", "Sanitary installation"],
      standards: [],
      applications: ["Residential", "Commercial", "Industrial", "Institutional"],
      features: ["Pressure-tested installations", "Multi-trade coordination"],
      image: stock.plant,
    },
    {
      slug: "general-building",
      name: "General Building",
      sectionOrder: compactOrder,
      shortName: "Building",
      tagline: "Building works from foundations to finishes.",
      summary:
        "Behind the MEP, Atheer's general building capability takes projects from foundation through structure and finishes — with the in-house mechanical, electrical and plumbing teams already on site.",
      capacity: "Villa → industrial",
      series: ["Structural building works", "Finishes & fit-out"],
      standards: [],
      applications: ["Residential developments", "Industrial buildings", "Educational", "Community facilities"],
      features: ["Single contractor accountability", "Integrated MEP delivery"],
      image: stock.plant,
    },
    {
      slug: "facility-maintenance",
      name: "Facility Maintenance",
      shortName: "Maintenance",
      sectionOrder: compactOrder,
      tagline: "Ongoing MEP maintenance for the buildings we build — and many we don't.",
      summary:
        "Atheer maintains completed buildings and systems on an ongoing basis — keeping mechanical, electrical and plumbing assets running through their full lifecycle.",
      capacity: "Ongoing AMC",
      series: ["Preventive maintenance", "Breakdown response", "System health audits"],
      standards: [],
      applications: ["Completed buildings", "Operational facilities", "Multi-site portfolios"],
      features: ["In-house technicians", "Scheduled preventive visits"],
      image: stock.plant,
    },
  ],
};

const burjAlDar: ProspectConfig = {
  slug: "burj-al-dar",
  companyName: "Burj Al Dar Building Contracting",
  displayName: "Burj Al Dar",
  industry: "contracting",
  established: 2016,
  location: "Industrial Area 13, Sharjah, United Arab Emirates",
  slogan: "Building Sharjah — from foundations to handover.",
  metaRole: "building construction & general contracting",
  hero: {
    kicker: "Est. 2016 · Industrial Area 13, Sharjah · Building contractor",
    headlineTop: "Building Sharjah,",
    headlineAccent: "one landmark",
    headlineBottom: "at a time.",
    subline:
      "Burj Al Dar is a Sharjah-based building contractor with a rich portfolio of warehouses, industrial buildings and residential projects — delivered on time, on budget and built to last.",
  },
  branding: {
    primaryColor: "#8A5A2B",
    secondaryColor: "#6B451F",
    accentColor: "#C77E3B",
    tintColor: "#F7EFE6",
  },
  contact: {
    email: "",
    address: "Warehouse 8/3, Industrial Area 13, Sharjah, United Arab Emirates",
    phone: "+971 50 425 5045",
  },
  socialProof: {
    googleRating: 4.6,
    reviewCount: 40,
    keywords: ["Building Construction", "General Contracting", "Industrial Buildings", "Warehouses"],
  },
  certifications: [],
  markets: ["Sharjah", "Dubai", "Northern Emirates", "UAE"],
  facilities: [
    "Industrial Area 13, Sharjah — base of operations",
    "In-house construction crews",
    "Full construction scope — structure to finishes",
  ],
  images: {
    officeBanner: stock.building,
    aerial: stock.urban,
    factorySharjah: stock.office,
    heroPoster: stock.cityscape,
    showreelPoster: stock.city,
  },
  projects: [
    {
      name: "Building Project 01",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Industrial Warehouse",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Residential Villa",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Commercial Building",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Warehouse Facility",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Villa Project",
      location: "Sharjah, UAE",
      img: stock.building,
    },
    {
      name: "Industrial Facility",
      location: "Sharjah, UAE",
      img: stock.building,
    },
  ],
  featuredServiceSlug: "building-construction",
  designDirection: baseDesign,
  automation: [
    "Enquiry received",
    "AI qualification",
    "Project type matched",
    "Lead created",
    "Contract team notified",
    "Follow-up scheduled",
  ],
  cta: {
    heading: "Build with a contractor who finishes.",
    body: "Describe your project — a warehouse, an industrial building or a villa — and the Burj Al Dar team will respond with experience, a realistic programme and a straight answer on budget.",
  },
  voice: {
    brand: { initial: "BD", line1: "BURJ AL DAR", line2: "Est. 2016 · Sharjah" },
    nav: { homeBack: "Back to Burj Al Dar", quoteLabel: "Get a construction quote" },
    hero: {
      primaryCta: "Get a construction quote",
      secondaryCta: "See the portfolio",
      heroImageAlt: "Burj Al Dar — building construction in Sharjah",
      ghostText: "BUILDING SHARJAH · EST 2016",
      stats: [
        { value: "9+", label: "Years of construction experience" },
        { value: "30+", label: "Buildings delivered" },
        { value: "4.6", label: "Google rating · 40 reviews" },
        { value: "100%", label: "In-house construction crews" },
      ],
      contactCardLabel: "Call Burj Al Dar",
      chipsHeading: "Sharjah building contractor",
      scrollCue: "Built by Burj Al Dar",
    },
    trustLines: [
      "A Sharjah building contractor that finishes",
      "From foundations to full handover",
    ],
    servicesKicker: "What we build",
    servicesHomeHeading: "A portfolio built on Sharjah's industrial ground",
    servicesHomeBlurb:
      "Warehouses, industrial buildings and residential projects — delivered by a contractor with a reputation for finishing the job.",
    servicesIndexHeading: "{displayName} — construction services",
    servicesIndexBlurb:
      "{count} construction service lines, delivered by in-house crews across Sharjah, Dubai and the Northern Emirates.",
    serviceDetail: {
      overviewHeadingPrefix: "Burj Al Dar",
      figureCaptionSuffix: "built by",
      badge: "Built to last",
      footnote:
        "Every Burj Al Dar project is delivered by in-house crews with a realistic programme and no cost surprises — from site handover to the final handback.",
      },
    assistant: { fallbackEmail: "+971 50 425 5045" },
    },
  services: [
    {
      slug: "building-construction",
      sectionOrder: standardOrder,
      name: "Building Construction",
      shortName: "Construction",
      tagline: "Full building construction — foundations, structure and finishes.",
      summary:
        "Burj Al Dar delivers complete building projects from the ground up — foundations, structural works and finishes — with in-house crews and a track record across Sharjah's industrial and commercial buildings.",
      capacity: "Full scope",
      series: ["Foundations & structure", "External works", "Internal finishes"],
      standards: [],
      applications: ["Industrial buildings", "Warehouses", "Commercial buildings", "Community buildings"],
      features: [
        "In-house construction crews",
        "Realistic programmes, honest budgets",
        "Single point of responsibility",
      ],
      image: stock.building,
    },
    {
      slug: "industrial-warehouse-construction",
      name: "Industrial & Warehouse Construction",
      sectionOrder: compactOrder,
      shortName: "Warehouses",
      tagline: "Warehouses and industrial buildings engineered for heavy use.",
      summary:
        "Industrial Area 13 is home turf — Burj Al Dar builds warehouses and industrial facilities with the slab, cladding and services that stand up to real operational demands.",
      capacity: "Industrial scale",
      series: ["Warehouse shells", "Industrial facilities", "Fitted industrial units"],
      standards: [],
      applications: ["Warehousing", "Light manufacturing", "Logistics", "Storage facilities"],
      features: ["Industrial-grade construction", "Steel and concrete expertise"],
      image: stock.building,
    },
    {
      slug: "villa-residential-projects",
      name: "Villa & Residential Projects",
      sectionOrder: compactOrder,
      shortName: "Villas",
      tagline: "Villas and small residential buildings delivered complete.",
      summary:
        "From villa construction to small residential buildings, Burj Al Dar brings the same in-house crews and finish quality that define its commercial portfolio.",
      capacity: "Residential scale",
      series: ["Villa construction", "Small residential buildings"],
      standards: [],
      applications: ["Private villas", "Residential compounds", "Staff accommodation"],
      features: ["Clean finishes", "Coordinated services installation"],
      image: stock.building,
    },
    {
      slug: "renovation-refurbishment",
      name: "Renovation & Refurbishment",
      shortName: "Renovation",
      sectionOrder: compactOrder,
      tagline: "Structural and cosmetic renewal of existing buildings.",
      summary:
        "Burj Al Dar renovates and refurbishes existing structures — structural repairs, facade renewal, internal upgrades and extension works, executed without disrupting the surrounding site.",
      capacity: "Full renewal scope",
      series: ["Structural refurbishment", "Interior renovation", "Extension works"],
      standards: [],
      applications: ["Existing buildings", "Industrial upgrades", "Commercial refresh"],
      features: ["Site-aware phasing", "In-house demolition & rebuild"],
      image: stock.building,
    },
  ],
};

const bestair: ProspectConfig = {
  slug: "bestair",
  companyName: "Best Air Conditioning Works & Maintenance Services LLC",
  displayName: "BestAir",
  industry: "hvac",
  established: 2014,
  location: "Sharjah, United Arab Emirates",
  slogan: "Your comfort is our priority.",
  metaRole: "air conditioning & HVAC contractor",
  hero: {
    kicker: "Est. 2014 · Sharjah, UAE · HVAC works, services & maintenance",
    headlineTop: "Air conditioning,",
    headlineAccent: "engineered & maintained",
    headlineBottom: "across the UAE.",
    subline:
      "BestAir designs, installs and maintains air conditioning and HVAC systems for homes, businesses and industry — chillers, chilled-water systems, packaged rooftop units, cold rooms and full ducted installations, backed by 10+ years of field experience.",
  },
  branding: {
    primaryColor: "#0057A8",
    secondaryColor: "#00407F",
    accentColor: "#00A3E0",
    tintColor: "#E7F0F9",
  },
  contact: {
    email: "sales@bestairservices.com",
    address: "Sharjah, United Arab Emirates",
    phone: "+971 55 595 3986",
  },
  socialProof: {
    googleRating: 4.6,
    reviewCount: 12,
    keywords: ["HVAC Installation", "Chiller Maintenance", "Cold Rooms", "AC Works & Services"],
  },
  certifications: [],
  markets: ["Sharjah", "Dubai", "Ajman", "Umm Al Quwain", "Northern Emirates"],
  facilities: [
    "Field service teams across the Northern Emirates",
    "Chiller, chilled-water & cold room specialism",
    "Supply & install under one contract",
  ],
  images: {
    officeBanner: stock.home,
    aerial: stock.office,
    factorySharjah: stock.urban,
    heroPoster: stock.building,
    showreelPoster: stock.city,
  },
  projects: [
    {
      name: "Chiller Systems at Work",
      location: "Sharjah, UAE",
      img: stock.office,
    },
    {
      name: "Chilled Water Plant Service",
      location: "UAE",
      img: stock.office,
    },
    {
      name: "Rooftop Unit Installation",
      location: "UAE",
      img: stock.office,
    },
    {
      name: "Ducted System Installation",
      location: "UAE",
      img: stock.office,
    },
    {
      name: "Cold Room Installation",
      location: "Sharjah, UAE",
      img: stock.office,
    },
    {
      name: "BTU Metering Install",
      location: "UAE",
      img: stock.office,
    },
  ],
  featuredServiceSlug: "air-cooled-chiller-services",
  designDirection: baseDesign,
  automation: [
    "Enquiry received",
    "AI qualification",
    "Service matched",
    "Lead created in CRM",
    "Field team notified",
    "Follow-up scheduled",
  ],
  cta: {
    heading: "Cold again — guaranteed.",
    body: "Tell BestAir what's not working — a chiller, a chilled-water system, a cold room or a whole facility — and the field team will come back with a diagnosis, a plan and a date.",
  },
  voice: {
    brand: { initial: "BA", line1: "BESTAIR", line2: "Est. 2014 · UAE" },
    nav: { homeBack: "Back to BestAir", quoteLabel: "Book a service" },
    hero: {
      primaryCta: "Book a service",
      secondaryCta: "Explore services",
      heroImageAlt: "BestAir — air conditioning works, services and maintenance",
      ghostText: "YOUR COMFORT. OUR PRIORITY.",
      stats: [
        { value: "10+", label: "Years of HVAC works & services" },
        { value: "9", label: "Service lines — chillers to cold rooms" },
        { value: "4.6", label: "Client rating" },
        { value: "1", label: "Contract from diagnosis to maintenance" },
      ],
      contactCardLabel: "Call the field team",
      chipsHeading: "HVAC works & services",
      scrollCue: "Inside BestAir",
    },
    trustLines: [
      "10+ years of chiller & HVAC field experience",
      "Diagnosis, works and maintenance under one contract",
    ],
    servicesKicker: "Service lines",
    servicesHomeHeading: "From a single chiller to a whole chilled-water plant",
    servicesHomeBlurb:
      "Installation, renovation and maintenance across chillers, chilled-water systems, rooftop packages, ducted works, cold rooms and BTU metering.",
    servicesIndexHeading: "The complete {displayName} service range",
    servicesIndexBlurb:
      "{count} service lines covering the full HVAC lifecycle — design, install, renovate and maintain — delivered by BestAir field teams.",
    serviceDetail: {
      overviewHeadingPrefix: "BestAir",
      figureCaptionSuffix: "installed and maintained by",
      badge: "Field tested",
      footnote:
        "Every BestAir job is diagnosed before a quote, delivered on a confirmed date and backed by aftercare — from a single unit to a full plant.",
      },
    assistant: { fallbackEmail: "sales@bestairservices.com" },
    },
  services: [
    {
      slug: "air-cooled-chiller-services",
      sectionOrder: standardOrder,
      name: "Air-Cooled Chiller Services",
      shortName: "Chillers",
      tagline: "Diagnosis, works and maintenance for air-cooled chillers.",
      summary:
        "BestAir services air-cooled chiller plants of every size — fault diagnosis, refurbishment, preventive maintenance and emergency response, keeping plants running through the Gulf's peak season.",
      capacity: "All sizes",
      series: ["Chiller diagnosis", "Chiller refurbishment", "Scheduled maintenance", "Breakdown response"],
      standards: [],
      applications: ["Commercial buildings", "Industrial plants", "Hotels", "Data centres"],
      features: [
        "Diagnosis before any quote",
        "Pre-summer health checks",
        "24-hour breakdown response",
      ],
      image: stock.office,
    },
    {
      slug: "chilled-water-system-services",
      name: "Chilled Water System Services",
      sectionOrder: compactOrder,
      shortName: "Chilled Water",
      tagline: "FCU, AHU and chilled-water networks tuned to performance.",
      summary:
        "From fan coils to AHUs to the distribution network, BestAir commissions, retrofits and maintains chilled-water systems for optimum flow, temperature and energy use.",
      capacity: "Full network",
      series: ["FCU & AHU service", "Chilled-water retrofits", "System balancing", "Energy optimization"],
      standards: [],
      applications: ["Commercial towers", "Hotels", "Malls", "Hospitals"],
      features: ["Balancing & optimization", "Phased retrofit programs"],
      image: stock.office,
    },
    {
      slug: "packaged-rooftop-unit-services",
      name: "Packaged & Rooftop Unit Services",
      sectionOrder: compactOrder,
      shortName: "Rooftop",
      tagline: "Installation and renewal of packaged & rooftop AC units.",
      summary:
        "BestAir supplies, installs and services packaged and rooftop units for commercial and light-industrial spaces — matched to the load, installed cleanly and maintained for life.",
      capacity: "Packaged range",
      series: ["Rooftop unit supply", "Packaged installation", "Unit replacement"],
      standards: [],
      applications: ["Retail", "Industrial halls", "Warehouses", "Event spaces"],
      features: ["Load-matched selection", "Clean rooftop installs"],
      image: stock.office,
    },
    {
      slug: "fcu-ahu-ducted-systems",
      name: "FCU, AHU & Ducted Systems",
      sectionOrder: compactOrder,
      shortName: "Ducted",
      tagline: "Ducted distribution designed, installed and kept balanced.",
      summary:
        "BestAir designs and installs ducted distribution for commercial spaces — ductwork, grilles and diffusers — and services the AHU, FCU and VRF systems that feed them.",
      capacity: "Full scope",
      series: ["Duct design & installation", "AHU & FCU works", "VRF and mini-ducted systems"],
      standards: [],
      applications: ["Offices", "Retail", "Restaurants", "Healthcare"],
      features: ["Balanced airflow delivery", "Coordinated duct & unit installs"],
      image: stock.office,
    },
    {
      slug: "cold-room-solutions",
      name: "Cold Room Solutions",
      sectionOrder: compactOrder,
      shortName: "Cold Rooms",
      tagline: "Walk-in, freezer and blast rooms that hold temperature.",
      summary:
        "BestAir installs and maintains walk-in coolers, freezer rooms and blast chillers for food businesses — sized correctly and held at safe temperatures all year.",
      capacity: "Walk-in · blast",
      series: ["Walk-in coolers", "Freezer rooms", "Blast chillers & freezers"],
      standards: [],
      applications: ["Restaurants", "Supermarkets", "Caterers", "Food processing"],
      features: ["Correct heat-load sizing", "Temperature-holding installs"],
      image: stock.office,
    },
    {
      slug: "btu-metering-controls",
      name: "BTU Metering & Controls",
      shortName: "Metering",
      sectionOrder: compactOrder,
      tagline: "Fair, accurate BTU metering with live consumption data.",
      summary:
        "BestAir supplies and installs BTU metering and control systems for district-cooling and chiller-fed premises — accurate billing data and live consumption insight for tenants and facilities teams.",
      capacity: "Single unit → portfolio",
      series: ["BTU meter supply & install", "Remote monitoring", "Billing data reporting"],
      standards: [],
      applications: ["District cooling tenants", "Commercial buildings", "Multi-tenant facilities"],
      features: ["Accurate, auditable data", "Remote monitoring"],
      image: stock.office,
    },
  ],
};

const unitedGulf: ProspectConfig = {
  slug: "united-gulf",
  companyName: "United Gulf Engineering Services & Contracting",
  displayName: "United Gulf",
  industry: "mep",
  established: 2009,
  location: "Umm Al Quwain & Sharjah, United Arab Emirates",
  slogan: "15 success years — serving with integrity.",
  metaRole: "fire protection, AC, electrical & plumbing contractor",
  hero: {
    kicker: "Est. 2009 · Umm Al Quwain & Sharjah · MEP contractor",
    headlineTop: "Fire protection, AC,",
    headlineAccent: "power & water",
    headlineBottom: "— one contractor.",
    subline:
      "United Gulf Engineering delivers fire protection, air conditioning, electrical and plumbing works across the UAE — 15 years of installed projects, backed by AMC and MEP services that keep systems running.",
  },
  branding: {
    primaryColor: "#C8102E",
    secondaryColor: "#9E0C24",
    accentColor: "#F2A900",
    tintColor: "#FCEEF0",
  },
  contact: {
    email: "support@unitedgulfengg.com",
    address: "Umm Al Quwain, United Arab Emirates",
    phone: "+971 55 303 8372",
  },
  socialProof: {
    googleRating: 4.5,
    reviewCount: 18,
    keywords: ["Fire Protection", "HVAC", "Electrical Works", "Plumbing", "AMC"],
  },
  certifications: [],
  markets: ["Umm Al Quwain", "Sharjah", "Ajman", "Dubai", "Northern Emirates"],
  facilities: [
    "Umm Al Quwain base — serving the Northern Emirates",
    "Multi-trade MEP — fire, HVAC, electrical, plumbing",
    "Annual maintenance contracts across the portfolio",
  ],
  images: {
    officeBanner: stock.factory,
    aerial: stock.cityscape,
    factorySharjah: stock.plant,
    heroPoster: stock.workshop,
    showreelPoster: stock.city,
  },
  projects: [
    {
      name: "HVAC Installation",
      location: "Umm Al Quwain, UAE",
      img: stock.cityscape,
    },
    {
      name: "Fire Protection System Install",
      location: "UAE",
      img: stock.cityscape,
    },
    {
      name: "Chiller Plant Installation",
      location: "UAE",
      img: stock.cityscape,
    },
    {
      name: "Electrical Installation",
      location: "UAE",
      img: stock.cityscape,
    },
    {
      name: "Plumbing Works",
      location: "UAE",
      img: stock.cityscape,
    },
    {
      name: "AMC Commissioning",
      location: "UAE",
      img: stock.cityscape,
    },
  ],
  featuredServiceSlug: "fire-fighting-systems",
  designDirection: baseDesign,
  automation: [
    "Enquiry received",
    "AI qualification",
    "Trade matched",
    "Lead created",
    "Contract team notified",
    "Follow-up scheduled",
  ],
  cta: {
    heading: "Fire-safe, cool, powered and plumbed.",
    body: "Tell United Gulf which trade you need — fire protection, air conditioning, electrical, plumbing or a full MEP package — and the contracting team will respond with scope, programme and price.",
  },
  voice: {
    brand: { initial: "UG", line1: "UNITED GULF", line2: "Est. 2009 · UAE" },
    nav: { homeBack: "Back to United Gulf", quoteLabel: "Get a quote" },
    hero: {
      primaryCta: "Get a quote",
      secondaryCta: "Explore services",
      heroImageAlt: "United Gulf — fire protection, AC, electrical and plumbing",
      ghostText: "15 SUCCESS YEARS · SINCE 2009",
      stats: [
        { value: "15", label: "Success years — since 2009" },
        { value: "4", label: "Core trades — fire · HVAC · electrical · plumbing" },
        { value: "30+", label: "Project portfolio — gallery & installations" },
        { value: "24/7", label: "AMC support across the Northern Emirates" },
      ],
      contactCardLabel: "Call United Gulf",
      chipsHeading: "Multi-trade MEP",
      scrollCue: "Our installed work",
    },
    trustLines: [
      "15 success years (since 2009)",
      "Fire protection to plumbing — one contract",
    ],
    servicesKicker: "Our trades",
    servicesHomeHeading: "Four trades, one accountable contractor",
    servicesHomeBlurb:
      "Fire protection, air conditioning, electrical and plumbing — delivered by in-house teams with 15 years of installed projects behind them.",
    servicesIndexHeading: "{displayName} — the full MEP package",
    servicesIndexBlurb:
      "{count} core trades delivered across the UAE since 2009 — from design and installation to annual maintenance contracts.",
    serviceDetail: {
      overviewHeadingPrefix: "United Gulf",
      figureCaptionSuffix: "installed by",
      badge: "15 years installed",
      footnote:
        "Every United Gulf installation is delivered by in-house multi-trade teams and backed by annual maintenance contracts across the portfolio.",
      },
    assistant: { fallbackEmail: "support@unitedgulfengg.com" },
    },
  services: [
    {
      slug: "fire-fighting-systems",
      sectionOrder: standardOrder,
      name: "Fire Fighting Systems",
      shortName: "Fire",
      tagline: "Fire protection designed, installed and maintained to code.",
      summary:
        "United Gulf supplies and installs fire fighting and fire protection systems — sprinklers, extinguishing systems, hydrants and pumps — engineered to code and maintained for life.",
      capacity: "Full fire scope",
      series: ["Fire suppression systems", "Sprinkler & hydrant networks", "Fire pumps"],
      standards: [],
      applications: ["Commercial buildings", "Warehouses", "Industrial facilities", "Government"],
      features: ["Code-compliant design", "Approved materials & installs", "Ongoing inspection"],
      image: stock.cityscape,
    },
    {
      slug: "air-conditioning-systems",
      name: "Air Conditioning Systems",
      sectionOrder: compactOrder,
      shortName: "HVAC",
      tagline: "AC design, installation and maintenance for every building type.",
      summary:
        "The HVAC division designs and installs air conditioning for commercial and industrial buildings — chillers, AHUs, ducted distribution — and keeps them running through scheduled maintenance.",
      capacity: "Full HVAC scope",
      series: ["Chiller & central plant", "Ducted systems", "Maintenance & repair"],
      standards: [],
      applications: ["Commercial buildings", "Industrial", "Residential", "Hospitality"],
      features: ["Full design-assist", "In-house installation", "Scheduled AMC"],
      image: stock.cityscape,
    },
    {
      slug: "electrical-works",
      name: "Electrical Works",
      sectionOrder: compactOrder,
      shortName: "Electrical",
      tagline: "Power distribution and electrical installation to spec.",
      summary:
        "United Gulf installs power distribution, lighting and low-current systems across the buildings it serves — coordinated with fire, HVAC and plumbing for clean multi-trade delivery.",
      capacity: "Full electrical scope",
      series: ["Power distribution", "Lighting & controls", "Low-current systems"],
      standards: [],
      applications: ["Buildings", "Industrial", "Infrastructure"],
      features: ["Multi-trade coordination", "Testing & commissioning"],
      image: stock.cityscape,
    },
    {
      slug: "plumbing-works",
      name: "Plumbing Works",
      sectionOrder: compactOrder,
      shortName: "Plumbing",
      tagline: "Water supply and drainage installed and maintained.",
      summary:
        "The plumbing division delivers potable water, drainage and sanitary systems — installed to spec, pressure tested and covered by ongoing maintenance where needed.",
      capacity: "Full plumbing scope",
      series: ["Water supply", "Drainage & sanitary", "Pump systems"],
      standards: [],
      applications: ["Residential", "Commercial", "Industrial"],
      features: ["Pressure-tested installs", "Pump & booster systems"],
      image: stock.cityscape,
    },
    {
      slug: "amc-mep-services",
      name: "AMC & MEP Services",
      shortName: "AMC",
      sectionOrder: compactOrder,
      tagline: "Annual maintenance contracts that keep systems legal and running.",
      summary:
        "United Gulf's AMC division maintains fire, HVAC, electrical and plumbing systems across a portfolio of buildings — scheduled inspections, response and compliance in one contract.",
      capacity: "Ongoing contracts",
      series: ["Fire system AMC", "HVAC & MEP AMC", "Breakdown response"],
      standards: [],
      applications: ["Commercial buildings", "Industrial facilities", "Multi-site portfolios"],
      features: ["Single AMC across trades", "Scheduled inspections", "Rapid response"],
      image: stock.cityscape,
    },
  ],
};

const alTawoos: ProspectConfig = {
  slug: "al-tawoos",
  companyName: "Al Tawoos Al Abyadh Tech Cont. LLC",
  displayName: "Al Tawoos",
  industry: "hvac",
  established: 2012,
  location: "Yarmuk, Sharjah, United Arab Emirates",
  slogan: "100+ projects delivered across the Emirates.",
  metaRole: "HVAC & kitchen ventilation specialists",
  hero: {
    kicker: "Est. 2012 · Sharjah, UAE · HVAC & kitchen ventilation specialists",
    headlineTop: "Cooling the Emirates",
    headlineAccent: "kitchens & facilities",
    headlineBottom: "since 2012.",
    subline:
      "Al Tawoos engineers and maintains HVAC for restaurants, hospitals, malls and bakeries — from energy-saving kitchen ventilation to AMC contracts that some clients have renewed for seven years running.",
  },
  branding: {
    primaryColor: "#7C3AED",
    secondaryColor: "#5B21B6",
    accentColor: "#C084FC",
    tintColor: "#F1EBFE",
  },
  contact: {
    email: "info@tawoostech.com",
    address: "P.O. Box 78449, Yarmuk, Sharjah, United Arab Emirates",
    phone: "+971 58 170 5400",
  },
  socialProof: {
    googleRating: 4.8,
    reviewCount: 26,
    keywords: ["HVAC", "Kitchen Ventilation", "DCKV Energy Saving", "AMC Contracts", "Cladding"],
  },
  certifications: [],
  markets: ["Sharjah", "Dubai", "Abu Dhabi", "Northern Emirates", "UAE-wide"],
  facilities: [
    "Yarmuk, Sharjah — head office",
    "Kitchen ventilation & DCKV specialist team",
    "AMC portfolio across 20+ F&B brands",
  ],
  images: {
    officeBanner: stock.restaurant,
    aerial: stock.food,
    factorySharjah: stock.catering,
    heroPoster: stock.restaurant,
    showreelPoster: stock.food,
  },
  projects: [
    {
      name: "OAK Restaurant — Jumeirah",
      location: "Dubai, UAE",
      img: stock.restaurant,
    },
    {
      name: "Papparoti — Dubai Mall",
      location: "Dubai, UAE",
      img: stock.restaurant,
    },
    {
      name: "Kitchen Ventilation Install",
      location: "Sharjah, UAE",
      img: stock.restaurant,
    },
    {
      name: "Bounce — Mirdif",
      location: "Dubai, UAE",
      img: stock.restaurant,
    },
    {
      name: "Restaurant HVAC Fit-out",
      location: "Dubai, UAE",
      img: stock.restaurant,
    },
    {
      name: "Bakeries HVAC",
      location: "Sharjah, UAE",
      img: stock.restaurant,
    },
    {
      name: "Hospital Ventilation — Abu Dhabi",
      location: "Abu Dhabi, UAE",
      img: stock.restaurant,
    },
    {
      name: "NMC HVAC Maintenance",
      location: "Dubai, UAE",
      img: stock.restaurant,
    },
  ],
  featuredServiceSlug: "hvac-execution",
  designDirection: baseDesign,
  automation: [
    "Enquiry received",
    "AI qualification",
    "Service matched",
    "Lead created",
    "Tech team notified",
    "Follow-up scheduled",
  ],
  cta: {
    heading: "Cooler kitchens, lower energy bills.",
    body: "Tell Al Tawoos about your facility — a new kitchen vent, an AMC contract, or an HVAC installation — and the team will respond with a design, an energy saving estimate and a date.",
  },
  voice: {
    brand: { initial: "AT", line1: "AL TAWOOS", line2: "Est. 2012 · Sharjah" },
    nav: { homeBack: "Back to Al Tawoos", quoteLabel: "Book a survey" },
    hero: {
      primaryCta: "Book a survey",
      secondaryCta: "Explore services",
      heroImageAlt: "Al Tawoos — HVAC and kitchen ventilation across the Emirates",
      ghostText: "COOLER KITCHENS · LOWER BILLS",
      stats: [
        { value: "2012", label: "Established in the UAE" },
        { value: "100+", label: "Projects completed" },
        { value: "7", label: "Years on our longest AMC contract" },
        { value: "20+", label: "F&B brands maintained" },
      ],
      contactCardLabel: "Call or WhatsApp the team",
      chipsHeading: "Specialists, not generalists",
      scrollCue: "Our client kitchens",
    },
    trustLines: [
      "7-Management AMC — renewed for seven years",
      "Energy-saving DCKV kitchen ventilation",
    ],
    servicesKicker: "Service lines",
    servicesHomeHeading: "The HVAC team restaurants actually rehire",
    servicesHomeBlurb:
      "Kitchen ventilation, AMC contracts, execution and TAB — delivered for brands like Papparoti, Bounce, OAK and NMC, then renewed year after year.",
    servicesIndexHeading: "{displayName} — HVAC, ventilation & AMC",
    servicesIndexBlurb:
      "{count} service lines, from kitchen ventilation and execution to AMC — trusted by 20+ F&B brands across the Emirates.",
    serviceDetail: {
      overviewHeadingPrefix: "Al Tawoos",
      figureCaptionSuffix: "engineered and maintained by",
      badge: "Client-retained",
      footnote:
        "Every Al Tawoos project is delivered by specialist teams and backed by the AMC relationships clients renew — seven years in our longest case.",
      },
    assistant: { fallbackEmail: "info@tawoostech.com" },
    },
  services: [
    {
      slug: "hvac-execution",
      sectionOrder: standardOrder,
      name: "HVAC Execution",
      shortName: "Execution",
      tagline: "HVAC designed and installed for restaurants, malls and hospitals.",
      summary:
        "Al Tawoos executes HVAC installations end-to-end — design, equipment, installation and commissioning — for restaurant fit-outs, malls, hospitals and bakeries across the Emirates.",
      capacity: "Full execution",
      series: ["Design & load calculation", "Ducted systems", "VRF & split systems", "Commissioning"],
      standards: [],
      applications: ["Restaurants", "Malls", "Hospitals", "Bakeries", "Offices"],
      features: [
        "Specialist F&B engineering",
        "Commissioned & documented handovers",
        "Client-retained aftercare",
      ],
      image: stock.restaurant,
    },
    {
      slug: "kitchen-ventilation-dckv",
      name: "Kitchen Ventilation & DCKV",
      sectionOrder: compactOrder,
      shortName: "Kitchen Vent",
      tagline: "Energy-saving demand-control ventilation for commercial kitchens.",
      summary:
        "Al Tawoos designs and installs kitchen extract, supply and demand-control ventilation (DCKV) that trims energy use while keeping kitchens cool and within code — its bread-and-butter craft.",
      capacity: "Grease extract · supply · DCKV",
      series: ["Grease extract systems", "Fresh-air supply", "Demand control (DCKV)"],
      standards: [],
      applications: ["Commercial kitchens", "Restaurant fit-outs", "Catering facilities"],
      features: ["Energy-saving DCKV control", "Grease extract engineering", "Code-aware installs"],
      image: stock.restaurant,
    },
    {
      slug: "hvac-annual-maintenance",
      name: "HVAC Annual Maintenance",
      sectionOrder: compactOrder,
      shortName: "AMC",
      tagline: "Annual maintenance contracts clients renew for years.",
      summary:
        "Al Tawoos runs AMC contracts across restaurant groups, malls and health facilities — scheduled service, response and parts support that clients have renewed for as long as seven years.",
      capacity: "Annual contracts",
      series: ["Scheduled preventive service", "24/7 breakdown response", "Filter & coil programs"],
      standards: [],
      applications: ["Restaurant groups", "Malls & retail", "Healthcare", "Commercial buildings"],
      features: ["Multi-year partnerships", "Coordinated scheduling", "Priority response"],
      image: stock.restaurant,
    },
    {
      slug: "hvac-maintenance-repair",
      name: "HVAC Maintenance & Repair",
      sectionOrder: compactOrder,
      shortName: "Maintenance",
      tagline: "Same-day repairs and health checks that protect equipment.",
      summary:
        "Beyond AMC, Al Tawoos responds to breakdowns and runs health checks across AC and ventilation equipment — diagnosing fast to protect comfort and food-safety temperatures.",
      capacity: "One-off · recurring",
      series: ["Breakdown repair", "Health checks", "Pre-summer servicing"],
      standards: [],
      applications: ["Restaurants", "Offices", "Retail", "Hospitals"],
      features: ["Fast diagnosis", "Genuine compatible parts"],
      image: stock.restaurant,
    },
    {
      slug: "tab-works",
      name: "TAB Works",
      sectionOrder: compactOrder,
      shortName: "TAB",
      tagline: "Testing, adjusting and balancing for safe, efficient airflow.",
      summary:
        "Al Tawoos performs testing, adjusting and balancing (TAB) on ducted systems — verifying airflow, pressures and performance so systems deliver what they were designed to.",
      capacity: "System balancing",
      series: ["Airflow measurement", "System adjustment", "Performance verification"],
      standards: [],
      applications: ["New installations", "Existing facilities", "Retrofit projects"],
      features: ["Documented results", "Performance verification"],
      image: stock.restaurant,
    },
    {
      slug: "cladding-works",
      name: "Cladding Works",
      shortName: "Cladding",
      sectionOrder: compactOrder,
      tagline: "Duct and equipment cladding that respects the ceiling.",
      summary:
        "Al Tawoos supplies and installs cladding for ducts and equipment — insulation, weatherproofing and neat, clean finishes that protect systems and respect interiors.",
      capacity: "Full cladding scope",
      series: ["Duct cladding & insulation", "Equipment boxing", "Weatherproofing"],
      standards: [],
      applications: ["Commercial kitchens", "Malls", "Buildings", "Industrial"],
      features: ["Clean finishes", "Protective insulation"],
      image: stock.restaurant,
    },
  ],
};

export const sharjahBatch: ProspectConfig[] = [geo, aljunaid, atheer, burjAlDar, bestair, unitedGulf, alTawoos];